# Generated by Django 4.0.3 on 2022-03-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rider_order',
        ),
    ]
