# Generated by Django 4.0.3 on 2022-04-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_rider_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='rider_id',
            new_name='user',
        ),
    ]
