# Generated by Django 4.0.3 on 2022-03-14 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='restaurant_id',
            field=models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
