# Generated by Django 4.0.3 on 2022-03-29 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_general_user_remove_user_is_general_and_more'),
        ('restaurant', '0010_alter_restaurant_owner_id_delete_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
