# Generated by Django 4.0.3 on 2022-03-30 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='owner_id',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, to='restaurant.owner'),
        ),
    ]
