# Generated by Django 4.0.3 on 2022-03-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_address_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address_model',
            name='detail_address',
        ),
    ]
