# Generated by Django 4.0.3 on 2022-03-25 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_address_model_address_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address_model',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address_model',
            name='address_id',
            field=models.AutoField(db_column='address_id', primary_key=True, serialize=False),
        ),
    ]
