# Generated by Django 4.0.3 on 2022-03-29 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_address_model_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='general_user',
            fields=[
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_general',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
