# Generated by Django 4.0.3 on 2022-04-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_rename_total_address_address_model_address_string_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_user',
            name='main_address',
            field=models.ForeignKey(db_column='main_address', default='', on_delete=django.db.models.deletion.PROTECT, to='authentication.address_model'),
        ),
    ]
