# Generated by Django 4.0.3 on 2022-03-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_basket_basket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
