# Generated by Django 4.0.3 on 2022-03-14 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_product_product_name'),
        ('order', '0003_alter_basket_basket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='restaurant.product'),
        ),
    ]
