# Generated by Django 4.0.3 on 2022-03-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='order_detail_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
