# Generated by Django 4.0.3 on 2022-03-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_basket_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user_id',
        ),
    ]
