# Generated by Django 4.0.3 on 2022-03-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_username_basket_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
