# Generated by Django 4.0.3 on 2022-03-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_restaurant_owner_id_delete_owner'),
        ('order', '0009_alter_order_detail_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='restaurant.product'),
        ),
    ]
