# Generated by Django 4.0.3 on 2022-03-29 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_general_user_remove_user_is_general_and_more'),
        ('order', '0011_alter_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user_id',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='authentication.general_user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.general_user'),
        ),
    ]
